# Generated by Django 2.0.4 on 2018-04-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=75)),
                ('credithours', models.IntegerField(db_column='CreditHours')),
                ('instructorname', models.CharField(db_column='InstructorName', max_length=100)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationdate', models.DateTimeField(db_column='RegistrationDate')),
            ],
            options={
                'managed': False,
                'db_table': 'Registeration',
            },
        ),
    ]
